### ISSUE TITLE
[Tracking] QSP-7 User might use untrusted authenticators

### ISSUE THREAD

**Issue by fmorency** [liftedinit/many-rs#137]
- [ ] Validate the attestation certificate
- [ ] Ensure that the authenticator used to sign the attestation is an acceptable device (see FIDO metadata service v3)
- [ ] Ensure that the certificate used to sign the attestation is valid and has not been revoked
